apiVersion: v1
kind: Service
metadata:
  name: openmetadata-server-service
  namespace: default
spec:
  type: LoadBalancer
  ports:
  - name: om-server-port
    port: 8585
    targetPort: 8585
  # - name: om-admin-port
  #   port: 8686
  #   targetPort: 8686
  # - name: airflow-port
  #   port: 8080
  #   targetPort: 8080
  selector:
    app: open-metadata-server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: openmetadata-server-deployment
  namespace: default
  labels:
    app: open-metadata-server
spec:
  replicas: 3
  selector:
    matchLabels:
      app: open-metadata-server
  template:
    metadata:
      labels:
        app: open-metadata-server
    spec:
      volumes:
        - name: task-pv-storage
          persistentVolumeClaim:
            claimName: task-pv-claim 

      containers:
      - name: openmetadata-server-container
        image: docker.getcollate.io/openmetadata/server:1.6.3
        workingDir: /opt/openmetadata
        command: ["sh", "-c"]
        args: 
          # - bootstrap/openmetadata-ops.sh migrate
          - bin/openmetadata-server-start.sh conf/openmetadata.yaml
        
        imagePullPolicy: Always
        env:
          - name: LOG_LEVEL
            value: INFO
          - name: DB_USER
            value: "admin"
          - name: DB_USER_PASSWORD
            value: "33v4Heb57fl5f5QI71OI"
          - name: DB_HOST
            value: "database-2.czimcyw6g02w.ap-south-1.rds.amazonaws.com"
          - name: OM_DATABASE
            value: "openmetadata_db"
          - name: SEARCH_TYPE
            value: "opensearch"
          - name: ELASTICSEARCH_HOST
            value: "search-openmetadata-domain-sccvtmu5mz73o62b3lvpvxwipa.ap-south-1.es.amazonaws.com"
          - name: ELASTICSEARCH_SCHEME
            value: "https"
          - name: ELASTICSEARCH_PORT
            value: "443"
          - name: ELASTICSEARCH_USER
            value: "admin"
          - name: ELASTICSEARCH_PASSWORD
            value: "33v4Heb57fl5f5QI71OI#"
          - name: OM_MONITOR_REGION
            value: "ap-south-1"
          - name: OM_MONITOR_ACCESS_KEY_ID
            value: "AKIARYEUCZ3WW4G4WC4O"
          - name: OM_MONITOR_ACCESS_KEY
            value: "muhCcOIwsgywrQDdo3BcgDyDmkYox8JpnZ0+o4PC"
          - name: PIPELINE_SERVICE_CLIENT_ENDPOINT
            value: "https://2589396f-7fc3-40b4-9f5f-8afd642a4bcd.c6.ap-south-1.airflow.amazonaws.com"
          # - name: PIPELINE_SERVICE_CLIENT_SECRETS_MANAGER_LOADER
          #   value: "db"
          - name: SERVER_HOST_API_URL
            value: "http://affb058d3bc904503951fe8f22cea490-1148072198.ap-south-1.elb.amazonaws.com:8585/api"
          - name: SECRET_MANAGER
            value: "db"
          - name: OM_SM_REGION
            value: "ap-south-1"
          - name: OM_SM_ACCESS_KEY_ID
            value: "AKIARYEUCZ3WW4G4WC4O"
          - name: OM_SM_ACCESS_KEY
            value: "muhCcOIwsgywrQDdo3BcgDyDmkYox8JpnZ0+o4PC"
        volumeMounts:
          - mountPath: /var/logs
            name: task-pv-storage

        ports:
          - name: server
            containerPort: 8585
